### ISSUE TITLE
Provide the ability to Sign Out of a Venue.

### ISSUE THREAD

**Issue by Tyfy** [nhsx/covid-19-app-android-ag-public#1]
At the moment there only appears to be an option to sign in to a Venue.

There should be the option to sign out so that if someone visits the same Venue but hours apart then they are not automatically seen as being there at the same time and at high risk of transmission.

e.g. Athletics events 

**Scenario 1:**

- parent accompanying an athlete arrive at a venue at 9am and leaves at 11am
- second parent who test positive arrives at the same venue at 1pm and leaves at 2pm

- No Match

**Scenario 2:**

- parent accompanying an athlete arrive at a venue at 9am and leaves at 11am
- second parent who test positive arrives at the same venue at 10am and leaves at 11:30

- Possible Match

It should be easy to sign out of a Venue when signing in to another one and either scan a QR Code or have a "Leave Venue" button in app to sign out when leaving.

**Comment by ataraxia89** [comment]
Does this need to be added to the iOS app also?

**Comment by NameOfTheDragon** [comment]
> Does this need to be added to the iOS app also? And what is the current process for tracking users in venues? Surely they can't be signed in indefinitely?

Anecdotal evidence gleaned from Facebook (so perhaps not totally reliable) suggests that they are "automatically checked out at midnight"

**Comment by ataraxia89** [comment]
Ugh don't get me started on Facebook 🤦‍♂️. Even if that's the case I think this should be undesired behaviour due to large potential of false positives.

**Comment by rick89lee** [comment]
Not anecdotal. Its mentioned in the common questions.

https://faq.covid19.nhs.uk/article/KA-01134

**Comment by ataraxia89** [comment]
Yeah it also confirms this on the app after scanning, this is clearly desired behaviour and suggests the locations may not be being used to calculate the individual user's risk level. This issue should be closed.

**Comment by elyobelyob** [comment]
"An app user is able to check in to a venue by scanning the QR code using the NHS COVID-19 App. When they check in, the venue name, date and time is shown to the user so they can verify the details (and cancel if necessary). The venue name, unique poster ID, date and time are stored on their device for up to 21 days, and this list is visible to the user. The user is able to delete any entries from this list."

** There is no such ability to delete entries or view entries.

**Comment by ataraxia89** [comment]
@Tyfy please can you close this issue?

**Comment by Tyfy** [comment]
Having read the FAQ that it logs you out at midnight or when you log into another venue but doesn't ask you to log out of the venue when you leave I don't see the point in keeping you logged in at all on the app.

If all it is doing is recording venues you visit then why not just log it and move on. 

It can show you the last time you logged in somewhere instead of saying that you are currently logged in.

I still this this is a feature that should be implemented and would prefer for someone associated with the project to actually confirm that they are reviewing issues here and comment or close the issue themselves.

Is that not the point in them putting the code here in the first place and allowing issues to be raised by non project devs or is this just fire and forget.

**Comment by ataraxia89** [comment]
@Tyfy they have already addressed this exact issue in the link provided above, therefore it is irrelevant, don't be implemented and should be closed.

**Comment by Tyfy** [comment]
I am closing this as although the issue hasn't been addresses as described I don't believe that this is being monitored by people that can actually affect development anyway.

As my country now has it's own app due to the time taken and lack of information about development of this version I have lost interest in trying to help and now couldn't care less.
