### ISSUE TITLE
Postal district suggestion during onboarding

### ISSUE THREAD

**Issue by skenaja** [nhsx/covid-19-app-android-ag-public#2]
https://github.com/nhsx/covid-19-app-android-ag-public/blob/ce3fe43da16392f9d8325656a64aa2df7d0b5cf8/app/src/main/res/values/strings.xml#L56

Although this is dummy data, it's potentially confusing to users as it's not an obvious-looking postal district that people will be familiar with. There only a few districts in London with letter suffixes.

Given the new [validation against real districts](https://github.com/nhsx/covid-19-app-android-ag-public/blob/ce3fe43da16392f9d8325656a64aa2df7d0b5cf8/app/src/main/java/uk/nhs/nhsx/covid19/android/app/onboarding/postcode/PostCodeValidator.kt#L11) in ce3fe43, I'd suggest it might be better to use real-world examples when onboarding new users (such as E2, L36, PO30 as used in string `valid_post_code_is_required`, areas where the app is currently being trialled).

**Comment by martinzue** [comment]
Thanks for the suggestion. We verified this with our product team. As we already improved this by giving 3 examples instead of 1, we'll leave it. Thanks again and stay healty.

**Comment by nhs-covid19** [comment]
Thanks for your interest in the NHS Covid-19 project. The onboarding journey has been updated, and I'm not sure that this issue still exists, so will close.
