### ISSUE TITLE
Transferring the COVID-19 app to a new phone loses all the data

### ISSUE THREAD

**Issue by zmarties** [nhsx/covid-19-app-android-ag-public#23]
**Describe the bug**
When you setup a new Android phone you normally transfer your apps and settings from your old phone as part of that set up.  This is achieved easily via the setup wizard, which just asks you to attach a cable between the two phones, and it goes ahead and transfers the apps and data from the old phone automatically.

Unfortunately, unlike properly written apps, the COVID-19 app does not allow its data to be transferred.  When you come to use the COVID-19 app on the new phone, it is as if you have just installed it for the first time - it walks you through the age check, and the postcode entry, and none of your previous checkins are maintained.

**To Reproduce**
1. Install the COVID-19 app on your existing phone.  Use it as normal, so you will accumulate a history of checkins.
2. Buy a new phone
3. Turn it on, and follow the instructions to transfer your apps and settings from the old phone.
4. Start the COVID-19 app on the new phone - it has forgotten all your settings and checkins.

**Expected behavior**
The new phone retains all your settings such as the postcode, and all your checkins.

**Screenshots**
n/a

**Smartphone (please complete the following information):**
 - Stock Android (on a Pixel device)

**Additional context**
I think this is because the Android manifest file has this line in it:
        android:allowBackup="false"
That line should not be present in properly written apps.

**Comment by barnstorm3r** [comment]
I wonder if this could be some kind of deliberate privacy decision to make sure that exposure data etc doesn't leave the device.

**Comment by nhs-covid19** [comment]
Thanks for your interest in the NHS Covid-19 project. Once a backup is taken, we can no longer control what happens to the data contained within. As such we would prefer that any application data resides only on the device, and we have a backup policy that enforces this. This is better in terms of privacy for the application user, and is in line with the backup policies for Exposure Keys (which are controlled by the operating system) on the underlying device.
