### ISSUE TITLE
Possible COVID-19 Exposure notification should click through to more information

### ISSUE THREAD

**Issue by mrjonstrong** [nhsx/covid-19-app-android-ag-public#25]
**Describe the bug**
The "Possible COVID-19 Exposure" notification does not click through to any useful information about why it was generated.

**To Reproduce**
An exposure is generated which falls below the threshold for further action, but is notified to the user by the operating system.

**Expected behaviour**
If the notification cannot be suppressed, clicking should take the user to a view which explains that this exposure is below the threshold for further action.

**Screenshots**
![image](https://user-images.githubusercontent.com/42520909/95175296-31bde100-07b3-11eb-92c8-6df754f048fb.png)

**Smartphone (please complete the following information):**
 - Device: Pixel 2
 - OS: Android 11
 - Version Build number RP1A.200720.009
 - App Version 3.6.2(73)

**Additional context**
Also reported on the iOS app https://github.com/nhsx/covid-19-app-ios-ag-public/issues/11

**Comment by nhs-covid19** [comment]
Thanks for your interest in the NHS Covid-19 project. We do welcome product suggestions on the above link - https://faq.covid19.nhs.uk/create-case/ and endeavour to respond to technical issues here. We are constantly looking at ways to improve the messaging & clarity of language within the app. Some improvements in this area have been deployed into version 3.7 of the app, now on the Play Store, and others will follow.
