### ISSUE TITLE
The way to change the entered postcode is non-obvious

### ISSUE THREAD

**Issue by gavanfantom** [nhsx/covid-19-app-android-ag-public#27]
**Describe the bug**
On first installation, the app asks for a (partial) postcode. Once this is entered, there is no way to later change it, for example if you are moving house, without clearing all of the app data.

[Edit: There is a way, it's just not particularly easy to find]

**To Reproduce**
1. Install the app
2. Open the app
3. Complete the initial configuration, including entering a partial postcode
4. Search through all of the menus
5. Fail to find any way to change the postcode

**Expected behavior**
It should be possible to change the postcode without clearing all of the app data and losing potential exposure notifications

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S20
 - OS: 10

**Comment by mrjonstrong** [comment]
Hi @gavanfantom ,

Have you tried:
Open the app
Click "About this app"
Click "Manage my data"
Select Edit next to postcode district. 
Enter a new postcode.
Click Save.

Does that work for you?

**Comment by mrjonstrong** [comment]
Hi @gavanfantom , 
Just found this which might help too. 

https://faq.covid19.nhs.uk/article/KA-01131/en-us

**Comment by gavanfantom** [comment]
Wow, that was quite well hidden. Thanks for the pointers.

Would you consider adding a link to the "Manage my data" from a more obvious place? The first place I would think of would be on the Risk level page, as that is where people primarily interact with the postcode district. Something like "Not your postcode?" somewhere near the bottom of the page would work well, I would imagine.
