### ISSUE TITLE
Exposure notifications disappear and no countdown clock

### ISSUE THREAD

**Issue by lstodd** [nhsx/covid-19-app-android-ag-public#35]
**Describe the bug**
User receives a notification saying they might have been in contact with someone who has tested positive for COVID-19 and they need to self isolate. They then click on the notification which causes the app to open. When the app opens, the notification disappears related to [issue #32](https://github.com/nhsx/covid-19-app-android-ag-public/issues/32) and there is no countdown clock to tell you when your self isolation ends. There is no information telling you where or when the exposure might have happened (was it a month ago or yesterday?). There are many reports of this happening.

**To Reproduce**
1. Download NHS contact tracing app
2. Wait for possible exposure notification
3. Click on notification
4. App opens and no information is provided about possible exposure or isolation. 

**Expected behavior**
User receives a possible COVID-19 exposure notification and that they need to self isolate. User clicks on notification which opens the app and provides them with more information about the possible exposure and a countdown clock on when their self isolation should end. Where users have not been exposed to COVID-19, they receive no exposure notifications.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Google Pixel 2
 - OS: Android 11
 - Version 3.7.2 (85)

**Additional context**
There are reports on twitter and in the media that if a user receives one of these notifications, and it disappears when the user clicks on it, that it might be a bug in the app and the user has not actually been exposed to COVID-19. Along with a bug fix, clear guidance should be released on how to treat different notification messages and expected behavior of alerts.

**Comment by nhs-covid19** [comment]
Thanks for your interest in the NHS Covid-19 project. Quite a few exposure related items have been updated and clarified in the latest release of the app (v3.9), including the use of the GAEN v2 API, which will remove notifications for contact events that don't result in isolation notifications. Further information is available in the NHS Covid-19 FAQ at https://faq.covid19.nhs.uk/article/KA-01325/en-us
