### ISSUE TITLE
Other NHS and ONS tests to be able to be recorded

### ISSUE THREAD

**Issue by cathrynsymons** [nhsx/covid-19-app-android-ag-public#9]
Please consider making it possible to record other tests, such as those given in hospitals and through the ONS survey.  That would allow better detection of contacts.

https://twitter.com/NHSCOVID19app/status/1309446092057202689

**Comment by ataraxia89** [comment]
This has also been reported on the iOS app here >> https://github.com/nhsx/covid-19-app-ios-ag-public/issues/7

Though it may need to be reported on the shared/backend project instead of these two, can somebody confirm?

**Comment by bdsl** [comment]
According to https://www.itv.com/news/2020-09-26/nhs-covid-19-contact-tracing-app-officials-working-to-fix-issue-of-processing-coronavirus-test-results this is fixed.

**Comment by ataraxia89** [comment]
This has been fixed and has now been reported via numerous sources. Contact tracers are now issuing codes that can be entered into the app after receiving the test results.

@cathrynsymons please can you close this issue?

**Comment by cathrynsymons** [comment]
Thank you, that was very quick.  And well done.

**Comment by bdsl** [comment]
@cathrynsymons Maybe. I might have been a bit hasty passing on the message from ITV that this is fixed. [Dr Michael Veale  was not convinced by it](https://twitter.com/mikarv/status/1310182243365801984).

**Comment by ataraxia89** [comment]
@bdsl nobody seems to be paying any attention to these GitHub issues anyway, I've almost given up.

**Comment by ataraxia89** [comment]
@bdsl from the horse's mouth >> https://mobile.twitter.com/NHSCOVID19app/status/1309946799164141569
